name: Deploy Portfolio
on:
  push:
    branches:
      - main

jobs:
  deploy_Portfolio:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@0.5.4
        with:
          ssh-private-key: ${{secrets.EC2_Key}}

      - name: Ensure SSH directory exists
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add SSH Known host
        run: ssh-keyscan -H ${{secrets.EC2_HOST}} >> ~/.ssh/known_host

      - name: Build Project
        working-directory: ./portfolio
        run: npm run build

      - name: Copy Portfolio Files to EC2
        run: |
          ssh ${{secrets.EC2_USER}}@${{secrets.EC2_HOST}} '
            rm -rf /var/www/portfolio
            mkdir /var/www/portfolio
          '
          rsync -avz -e "ssh" ./portfolio/build ${{secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/var/www/portfolio
